export const BLACK_CARDS = [
  "Nature documentary: the tall grass parts and the camera zooms in on ____.",
  "Grainy security footage, 3:00 AM: the office vending machine is being robbed by ____.",
  "Classic sitcom: the laugh track roars as the family sits down to dinner with ____.",
  "Heist movie, final act: the vault door groans open, revealing ____.",
  "Disaster movie: sirens wail across the city as millions flee in terror from ____.",
  "ASMR video: soft whispers, gentle tapping, and ____ in extreme close-up.",
  "Late-night infomercial: But wait, there's more! Order now and get ____ absolutely free!",
  "Music video, slow motion, wind machine on full blast: the camera circles ____ on the hood of a glittering sports car.",
  "Wedding video: the guests gasp as the bride walks down the aisle arm in arm with ____.",
  "Cooking show finale: the judges lift the silver dome to reveal ____.",
  "Black-and-white noir, rain on the window: the detective clicks on his desk lamp and sees ____ sitting in the client's chair.",
  "Mars colony, Day 400: something is knocking on the airlock, and the camera shows ____.",
  "A medieval tapestry comes to life as knights on horseback charge into battle against ____.",
  "Found-footage horror: the flashlight beam sweeps across the basement and lands on ____.",
  "Breaking news, live from the helicopter: police cars chase ____ down the empty highway at sunset.",
  "Sold-out monster truck rally: the crowd goes wild as the ramp launches ____ over twenty crushed cars.",
  "Park ranger bodycam: the ranger slowly unzips the tent and finds ____.",
  "Space epic: an armada of starships bows before ____ on the throne of the galaxy.",
  "Retro 1980s aerobics video: grab your leg warmers and follow along with ____!",
  "Western showdown at high noon: the tumbleweeds roll as the sheriff squares off against ____.",
  "1920s silent film: the hero, tied to the railroad tracks, is rescued at the last second by ____.",
  "Live weather report: the meteorologist clings to a lamppost in the hurricane, dodging ____.",
  "Baking competition: the contestants have two hours to sculpt a cake shaped like ____.",
  "1950s sci-fi B-movie: the townsfolk scream as the flying saucer beams down ____.",
  "Doorbell camera footage shows ____ carrying off my package.",
  "Monday's staff meeting is interrupted by ____ bursting through the conference room wall.",
  "Airport security pulls my carry-on aside, unzips it, and lifts out ____.",
  "Traffic camera, rush hour: all four lanes of the highway are blocked by ____.",
  "At the hair salon, the stylist spins the chair around, and my hair has been sculpted into ____.",
  "At the car dealership, the salesman whips off the silk sheet to unveil ____.",
  "The family portrait at the photo studio is photobombed by ____.",
  "Two samurai face off in a storm of cherry blossoms, but their duel is interrupted by ____.",
  "The deep-space telescope's first image comes back, and it shows ____ orbiting Saturn.",
  "Under the northern lights, a lone explorer discovers ____ frozen in a block of ice.",
  "At the bottom of the deepest ocean trench, the submarine's floodlights catch ____.",
  "Lightning strikes the mad scientist's tower, bringing to life ____.",
  "The Colosseum crowd roars as the lone gladiator turns to face ____.",
  "Grainy moon landing broadcast: the astronaut steps off the ladder and comes face to face with ____.",
  "Midnight at the natural history museum: the dinosaur skeleton wakes up and chases ____.",
  "Deep in the glittering underwater kingdom, the mermaid queen places her coral crown on ____.",
  "Inside a snow globe the size of a city, a grand parade marches behind ____.",
  "Moonlit masquerade ball in Venice: everyone on the dance floor is waltzing with ____.",
  "Grocery store camera, aisle five: the cereal shelves have just been flattened by ____.",
  "Opening ceremony of the World Games: the stadium goes dark as the torch is carried in by ____.",
  "Kindergarten show-and-tell: today, little Lily brought ____.",
];

export const WHITE_CARDS = [
  "a raccoon in a tiny tuxedo",
  "three goats in a trench coat",
  "a flock of sheep in astronaut helmets",
  "a herd of llamas in matching sunglasses",
  "a T. rex trying to put on a sweater",
  "a pigeon the size of a city bus",
  "a sloth in a full racing suit",
  "a crab in tiny sneakers",
  "a tower of forty stacked corgis",
  "a giraffe in a turtleneck",
  "a crocodile in a bubble bath",
  "a hippo ballerina in a pink tutu",
  "a bear in a chef's hat tossing pizza dough",
  "a cat flying a fighter jet",
  "a baby dragon sneezing fire",
  "a sea turtle with a jetpack",
  "a lobster the size of a pickup truck",
  "a cheerleading squad of grizzly bears",
  "a basset hound in a judge's wig",
  "a seagull stealing a giant pretzel",
  "a miniature horse in a ten-gallon hat",
  "a swarm of bees shaped like a man",
  "an eight-foot-tall chicken",
  "a gorilla in a wedding dress",
  "an octopus DJ with eight turntables",
  "a kangaroo in boxing gloves and a silk robe",
  "a cow strutting down a fashion runway",
  "a fifty-foot golden retriever with a tennis ball",
  "a swan in pearls on water skis",
  "a baby elephant in yellow rain boots",
  "a parrot with an eye patch and a peg leg",
  "a polar bear in a Hawaiian shirt",
  "a line of ants carrying a whole cupcake",
  "a shark wearing water wings",
  "a family of raccoons with rolling luggage",
  "a flock of pigeons in tiny hard hats",
  "two hundred penguins in a conga line",
  "a barbershop quartet of seals",
  "a poodle driving a steamroller",
  "a moose in a shower cap",
  "a hamster in full knight's armor",
  "a possum in a velvet opera cape",
  "a corgi riding a war elephant",
  "a snail with a jet engine",
  "a goldfish piloting a giant robot",
  "an ostrich on a pogo stick",
  "a hedgehog the size of a mountain",
  "a gang of ducklings in leather jackets",
  "a rhino on a tightrope",
  "a goose leading a cavalry charge",
  "a frog king on a lily pad throne",
  "a herd of bison in party hats",
  "a hummingbird wielding a tiny sword",
  "a squirrel jousting on a greyhound",
  "a walrus playing the bagpipes",
  "a piglet in a bow tie",
  "an alpaca with a pompadour",
  "a tiny wizard riding a mouse",
  "an elephant on a unicycle",
  "a sumo wrestler on roller skates",
  "a robot butler juggling flaming torches",
  "a ghost in a bedsheet riding a tandem bicycle",
  "a medieval baby with a grumpy old man's face",
  "a marching band of skeletons",
  "an elderly wizard on a hoverboard",
  "a nervous astronaut holding a birthday cake",
  "a bodybuilder made entirely of jelly",
  "a vampire slathered in sunscreen",
  "a lumberjack made of waffles",
  "a snowman sweating in a sauna",
  "a mummy unraveling on a treadmill",
  "a scarecrow conducting an orchestra of crows",
  "a businessman sprinting in a giant hamster wheel",
  "a gang of grandmas on motorcycles",
  "a synchronized swimming team of grandmas",
  "a magician pulling a horse out of a top hat",
  "an opera singer hitting a window-shattering note",
  "a ghostly lighthouse keeper holding a lantern",
  "a mermaid stuck in a kiddie pool",
  "an army of knights on rocking horses",
  "a lonely clown holding a single balloon",
  "a horde of toddlers in dinosaur costumes",
  "Bigfoot getting a pedicure",
  "Grandpa riding a lawnmower at full speed",
  "a dozen mimes trapped in invisible boxes",
  "a grown man in a chicken costume",
  "a suit of armor with nobody inside",
  "a hundred identical mannequins",
  "a Viking longship on roller skates",
  "a disco ball the size of the moon",
  "a pirate ship made of cheese",
  "a living mountain of spaghetti and meatballs",
  "a haunted porcelain doll on a moped",
  "a storm cloud raining bowling balls",
  "a stampede of wedding cakes on tiny legs",
  "a fleet of empty shopping carts rolling by themselves",
  "a fern with giant googly eyes",
  "a blimp shaped like a hot dog",
  "a pack of feral robot vacuums",
  "a glitter tornado",
  "a school bus with spider legs",
  "a burrito the size of a submarine",
  "a swarm of wind-up chattering teeth",
  "a thousand runaway beach balls",
  "a wheel of cheese the size of a car",
  "a squadron of toy helicopters",
  "a tiny thunderstorm with real lightning",
  "a downpour of rubber chickens",
  "a canoe full of mashed potatoes",
  "an avalanche of tennis balls",
  "a fire truck spraying chocolate pudding",
  "a walking pile of dirty laundry",
  "a bathtub with an outboard motor",
  "a cloud of giant soap bubbles",
  "a swimming pool full of jelly beans",
  "a bulldozer covered in birthday candles",
  "a catapult loaded with cream pies",
  "a wall of fog with glowing eyes",
  "a tidal wave of orange soda",
  "a flock of plastic lawn flamingos",
  "a melting ice sculpture of a whale",
  "a parade float shaped like a giant shrimp",
  "ten thousand paper airplanes",
  "a flotilla of swan-shaped paddleboats",
  "a frozen turkey on a skateboard",
  "a stack of pancakes as tall as a building",
  "a blizzard of shredded paperwork",
  "fifty glowing jellyfish",
  "a crop duster flying way too low",
  "a giant inflatable rubber duck",
  "a three-story garden gnome",
  "a lighthouse with chicken legs",
  "a flying grand piano",
  "a parade of dancing toasters",
  "a giant walking teapot",
  "a volcano erupting confetti",
  "a thundercloud with a handlebar mustache",
  "a lava lamp the size of a water tower",
  "a cardboard-box spaceship",
  "a banana peel the size of a football field",
  "a double-decker bus driven by a chimpanzee",
  "a hailstorm of gumballs",
  "a cowboy riding a giant tortoise",
  "a skyscraper-sized inflatable tube man",
  "an accordion player on stilts",
  "a hot air balloon shaped like a pig",
  "a regiment of toy soldiers marching in step",
  "a convoy of ice cream trucks",
  "a lost scuba diver with a treasure map",
  "a hot tub on a flatbed truck",
];
